# Generated by Django 5.2.8 on 2025-11-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='Kazakhstan', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(default='Asia/Almaty', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='MonitoringStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('openaq', 'OpenAQ'), ('aqicn', 'AQICN'), ('kazhydromet', 'Kazhydromet'), ('us_embassy', 'U.S. Embassy')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_reference', models.BooleanField(default=False, help_text='Is this a reference-grade station?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='domain.city')),
            ],
        ),
        migrations.CreateModel(
            name='AQICalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('aqi_value', models.IntegerField()),
                ('category', models.CharField(choices=[('good', 'Good (0-50)'), ('moderate', 'Moderate (51-100)'), ('unhealthy_sensitive', 'Unhealthy for Sensitive Groups (101-150)'), ('unhealthy', 'Unhealthy (151-200)'), ('very_unhealthy', 'Very Unhealthy (201-300)'), ('hazardous', 'Hazardous (301+)')], max_length=30)),
                ('dominant_pollutant', models.CharField(max_length=10)),
                ('pm25_aqi', models.IntegerField(blank=True, null=True)),
                ('pm10_aqi', models.IntegerField(blank=True, null=True)),
                ('o3_aqi', models.IntegerField(blank=True, null=True)),
                ('no2_aqi', models.IntegerField(blank=True, null=True)),
                ('so2_aqi', models.IntegerField(blank=True, null=True)),
                ('co_aqi', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aqi_calculations', to='domain.city')),
            ],
            options={
                'unique_together': {('city', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_timestamp', models.DateTimeField(db_index=True, help_text='Time for which forecast is made')),
                ('horizon_hours', models.IntegerField(help_text='Hours ahead from creation time')),
                ('model_type', models.CharField(choices=[('lstm', 'LSTM Neural Network'), ('svr', 'Support Vector Regression'), ('ensemble', 'Ensemble')], max_length=20)),
                ('model_version', models.CharField(max_length=50)),
                ('pollutant', models.CharField(default='pm25', max_length=10)),
                ('predicted_value', models.FloatField()),
                ('confidence_lower', models.FloatField(blank=True, null=True)),
                ('confidence_upper', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('error', models.FloatField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='domain.city')),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'forecast_timestamp'], name='domain_fore_city_id_338b99_idx'), models.Index(fields=['model_type', 'created_at'], name='domain_fore_model_t_eec762_idx')],
            },
        ),
        migrations.CreateModel(
            name='AirQualityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('pollutant', models.CharField(choices=[('pm25', 'PM2.5'), ('pm10', 'PM10'), ('o3', 'Ozone'), ('no2', 'Nitrogen Dioxide'), ('so2', 'Sulfur Dioxide'), ('co', 'Carbon Monoxide')], max_length=10)),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('µg/m³', 'Micrograms per cubic meter'), ('ppm', 'Parts per million'), ('ppb', 'Parts per billion')], default='µg/m³', max_length=10)),
                ('is_validated', models.BooleanField(default=False)),
                ('quality_flag', models.CharField(blank=True, max_length=20, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='domain.monitoringstation')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp', 'pollutant'], name='domain_airq_timesta_6533e8_idx'), models.Index(fields=['station', 'pollutant', 'timestamp'], name='domain_airq_station_3b7ee7_idx')],
                'unique_together': {('station', 'timestamp', 'pollutant')},
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Relative humidity in %', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='Atmospheric pressure in hPa', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in m/s', null=True)),
                ('wind_direction', models.FloatField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('precipitation', models.FloatField(blank=True, help_text='Precipitation in mm', null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='domain.city')),
            ],
            options={
                'unique_together': {('city', 'timestamp')},
            },
        ),
    ]
